### ISSUE TITLE
Rename Binary => Bytes

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-xdr-next#14]
Rename Binary to Bytes in the Val and Spec XDR

Binary is a somewhat confusing term. When I see it in the docs it doesn't scream at me that this is the type for storing byte slices or byte arrays. Doing a quick survey of Ethereum, they use the term Bytes in both Solidity and Vyper. Thinking back to whenever I have explained Binary to others or in my head, I immediately reach for the term "bytes" or "byte slice".

The term Bytes is what we're using at the SDK layer now since https://github.com/stellar/rs-soroban-sdk/pull/394.

**Comment by jonjove** [comment]
Was this resolved by #16?

**Comment by leighmcculloch** [comment]
It was! Thanks.
