### ISSUE TITLE
Merge stellar-xdr next branch to curr branch in preparation of Soroban launch

### ISSUE THREAD

**Issue by anupsdf** [stellar/stellar-xdr-next#144]
### Soroban XDR changes for launch
This is a tracking issue to merge the [next](https://github.com/stellar/stellar-xdr/tree/next) branch to curr branch in stellar-xdr repo in preparation for Soroban launch.

**Comment by leighmcculloch** [comment]
> merge

Fyi this may mean merge in the manual sense, not automatic sense, because the curr and next branches share no history in git.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-xdr/pull/147
