### ISSUE TITLE
Tag Protocol 19 of the XDR

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-xdr-next#54]
We should tag Protocol 19 and create a GitHub Release for it, and do so for future releases too. Potentially we could also do it for past releases.

We should be able to work out which commits to tag by looking at the stellar-core tag for a `vNN.0.0`, and then looking for the last commit to the xdr directory in stellar-core, and matching that to a commit in this repository.

cc @MonsieurNicolas

**Comment by leighmcculloch** [comment]
I think we can tag the following releases:
- `stellar-core`@`v19.0.0` (`9d0704eb`) last commit to `/src/xdr` is `11d39a56`. That commit on this repository is `d6a75a1`. So we can tag `d6a75a1` as `v19`.
- `stellar-core`@`v18.0.0` (`e381447a`) last commit to `/src/xdr` is `e381447a`. That commit on this repository is `c386b46`. So we can tag `c386b46` as `v18`.
- `stellar-core`@`v17.0.0` (`096f6a76`) last commit to `/src/xdr` is `66269ba4`. That commit on this repository is `173d37d`. So we can tag `173d37d` as `v17`.

We can do additional if we want, although not sure utility.

**Comment by leighmcculloch** [comment]
@MonsieurNicolas ☝🏻 How many should we do do you think?

**Comment by leighmcculloch** [comment]
I tagged and created GH releases for the above three. If anyone wants this to be done differently please reopen this issue and I can change them.

**Comment by MonsieurNicolas** [comment]
yeah this is plenty - thank you

**Comment by leighmcculloch** [comment]
Turns out I had made a mistake tagging v18 and v17. The commits above are correct, but I accidentally tagged the latest commit instead of the commits specified. So I just deleted v17 and v18 tags and releases, and will just leave it as the v19 one.
