### ISSUE TITLE
Include inSuccessfulContractCall for all events

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-xdr-next#77]
Context - https://github.com/stellar/soroban-tools/pull/536#discussion_r1149568828

**Comment by paulbellamy** [comment]
I don’t think this is necessary anymore. In https://github.com/stellar/go/blob/soroban-xdr-next/ingest/ledger_transaction.go#L185-L188, we “convert” normal events to DiagnosticEvents for the sake of go’s type system, by setting InSuccessfulContractCall = true on each one.
